### ISSUE TITLE
cant Compile Forks

### ISSUE THREAD

**Issue by Elecmcqueen** [joeSeggiola/arduino-eurorack-projects#2]
Hy,
I have trai to build your Forks Module.
The Scamatic ist gread and varry cheap but i cant combile youre code. The Arduino ide dont can find your lip.
I have tray various variations of save youre lip and compile as well. 
Arduino IDE cand find it.
you got a solution?

**Comment by joeSeggiola** [comment]
Hi. The `lib/` folder should be in the same folder as the sketch you are trying to compile. The repository uses links, but if they don't work, you could try copy and paste the folder: copy the entire `lib/` folder from the project root into the `forks/` directory.

If it still doesn't work, please report the exact error message.

**Comment by Elecmcqueen** [comment]
I have tray youre solution but no result.
I send you the Error Code :

C:\Users\Klang\Documents\Arduino\forks\forks.ino:31:10: fatal error: Led.cpp: No such file or directory

 #include "Led.cpp"

          ^~~~~~~~~

compilation terminated.

-------------------------------------------------------------------------------------------------------
i have copy the forks Projekt folder with lib file in it and have tray to compile = Error
i have tray to copy the lib Folder in the Forks Projekt Folder, but thats not possible, because there is the lib file in there. Windows cant do that.

thanks for youre Support
and cheers :)

**Comment by joeSeggiola** [comment]
Leave the include lines as they were originally:

```cpp
#include "lib/Led.cpp"
#include "lib/Button.cpp"
#include "lib/Knob.cpp"
```

And then copy the `lib/` folder into the Forks folder. If you can't do it, delete the `lib` file before: it is useless, it was the link file, but it's not working. You need to have something like this:

```
forks/
  forks.ino
  lib/
    Led.cpp
    Button.cpp
    Knob.cpp

**Comment by Elecmcqueen** [comment]
Yes Thats it !!! Verry thank you for help so fast !
